### ISSUE TITLE
NullReferenceException when using invalide job id

### ISSUE THREAD

**Issue by eXpl0it3r** [jobbrIO/jobbr-storage-mssql#9]
I think this may be related to a misunderstanding of the OrmLite interface. In EntityFramework `Single()` will thrown an exception if nothing is found, but in OrmLite it seems to just return `null`, which the consequently makes the `ToModel()` call fail.

## API Call

```
http://localhost:1337/jobs/4
```

Where `4` is a non-existent job id.

## Actual Behavior

NullReferenceException is thrown and returned to the API caller

## Expected Behavior

404 is returned to the API caller

## Relevant Code Pieces

https://github.com/jobbrIO/jobbr-storage-mssql/blob/6a8e5a06d0fb10d439ef2c8b4e427317a4b92bde/source/Jobbr.Storage.MsSql/MsSqlStorageProvider.cs#L75-L81

https://github.com/jobbrIO/jobbr-storage-mssql/blob/6a8e5a06d0fb10d439ef2c8b4e427317a4b92bde/source/Jobbr.Storage.MsSql/Mapping/JobMapping.cs#L7-L22

## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jobbr.Storage.MsSql.Mapping.JobMapping.ToModel(Job entity) in C:\projects\jobbr-storage-mssql\source\Jobbr.Storage.MsSql\Mapping\JobMapping.cs:line 9
   at Jobbr.Storage.MsSql.MsSqlStorageProvider.GetJobById(Int64 id) in C:\projects\jobbr-storage-mssql\source\Jobbr.Storage.MsSql\MsSqlStorageProvider.cs:line 79
   at Jobbr.Server.Storage.JobbrRepository.GetJob(Int64 id) in C:\projects\jobbr-server\source\Jobbr.Server\Storage\JobbrRepository.cs:line 27
   at Jobbr.Server.ComponentServices.Management.JobQueryService.GetJobById(Int64 id) in C:\projects\jobbr-server\source\Jobbr.Server\ComponentServices\Management\JobQueryService.cs:line 24
   at Jobbr.Server.WebAPI.Controller.TriggerController.GetTriggersForJob(Int64 jobId, Int32 page, Int32 pageSize, Boolean showDeleted) in C:\projects\jobbr-webapi\source\Jobbr.Server.WebAPI\Controller\TriggerController.cs:line 82
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by michaelschnyder** [comment]
good catch. definitely be handled before the mapping and translated into a 404. I assume it translated to a 500 also in the past, should there have been an exception (Dapper was used earlier)

I suggest to analyze other places where a similar mapping is made which could potentially fail. To mitigate, it might be reasonable to introduce a appropriate extension for OrmLite that throws an exception that can be translated by the API layer to a 404. Open for other suggestions.
